# =================================================
# Tasks API
# =================================================

### List by owner
GET http://localhost:7071/api/tasks?rtr=4&owner=dave


### List by assignee
GET http://localhost:7071/api/tasks?assignee=lou_reeds


### Get single by id
GET http://localhost:7071/api/tasks/eqzsq


### Create a task
POST http://localhost:7071/api/tasks
Content-Type: application/json

{
  "title": "wibble blah hat 2",
  "owner": "dave",
  "notes": "This is a test, bye!"
}


### Update a task
PUT http://localhost:7071/api/tasks
Content-Type: application/json

{
  "id": "wzLUK",
  "notes": "sdfdfsdfsdf",
  "assignedTo": [ "lou_reed" ]
}


### Delete a task
DELETE http://localhost:7071/api/tasks/ONy1ruuuu

# =================================================
# Users API
# =================================================

### Get all users
GET http://localhost:7071/api/users


### Create a user
POST http://localhost:7071/api/users
Content-Type: application/json

{
  "id": "53637e882dc34794aca9864e026acd2a",
  "name": "becolem@microsoft.com"
}

### Won't work locally
GET http://localhost:7071/api/postLogin

###

GET http://localhost:7071/api/debugger